export enum Config {
  DEFAULT_MAP_SIZE = 300,
  DEFAULT_ZOOM = 1,
  DEFAULT_BG_COLOR = 'white',
  DEFAULT_TEXTCOLOR = 'black',
  DEFAULT_MARKER_COLOR = 'blue',
  ZOOM_DISABLED = 'gray',
  ZOOM_TEXT = 'white',
  ZOOM_BG_COLOR = 'black',
  RESET_ICON = 'https://svgshare.com/i/iMJ.svg',
  RESET_SIZE = 17,
  STAIRS_ICON = 'https://svgshare.com/i/iPZ.svg',
  ZOOM_PLUS_ICON = 'https://svgshare.com/i/iPa.svg',
  ZOOM_MINUS_ICON = 'https://svgshare.com/i/iPb.svg',
  CLOSE_ICON = 'https://svgshare.com/i/iPy.svg',
}
